query getAllTripsOfPassenger($passengerId: String!) {
  getAllTripsOfPassenger(passengerId: $passengerId) {
    id
    date
    price
    status
    startLocation
    stopLocations
    endLocation
    driver {
      email
      firstname
      lastname
    }
    numberOfPassengers
    createdAt
    updatedAt
  }
}
