query GetReviewsFromAUser($userId: String!) {
  reviewsFromAUser(userId: $userId) {
    id
    rating
    comment
    type
    createdAt
    target {
      id
      firstname
      lastname
    }
  }
}
