mutation UpdateTrip($id: Float!, $data: TripUpdateInput!) {
  updateTrip(id: $id, data: $data) {
    id
    date
    price
    status
    startLocation
    stopLocations
    endLocation
    driver
    createdAt
    updatedAt
  }
}
