GET http://localhost:4000/driver

###

POST http://localhost:4000/driver
Content-Type: application/json

{
    "car": "A supprimer"
}

###

PUT http://localhost:4000/driver
Content-Type: application/json

{
    "id":3,
    "newDriver": {
        "car": "Mercedes"
    }
}

###

DELETE http://localhost:4000/driver
Content-Type: application/json

{
    "id":5
}