GET http://localhost:4000/trip

###

GET http://localhost:4000/trip?driver=3

###

GET http://localhost:4000/trip/1

###

POST http://localhost:4000/trip
Content-Type: application/json

{
    "title": "Car to sell",
    "date": "Mardi 20 février",
    "owner": "example@gmail.com",
    "price": 50,
    "passengers": 4,
    "driverId": "?",
    "status": "?",
    "startLocation" : "Paris",
    "endLocation" : "Lyon",
    "numberOfSeats" : "45645131"
  }

###

DELETE http://localhost:3000/trip
Content-Type: application/json

{
  "id": 2
}

###
PUT http://localhost:4000/trip
Content-Type: application/json

{
  "idToEdit": 4,
  "newTrip": {
    "driver": 2
  } 
}